apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-golang
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sa-golang-role
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sa-golang-rb
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sa-golang-role
subjects:
- kind: ServiceAccount
  name: sa-golang
  namespace: default
---
apiVersion: v1
kind: Pod
metadata:
  name: golang-client-pod
spec:
  containers:
  - name: golang-client
    image: golang
    command: ["sleep", "infinity"]
  serviceAccountName: sa-golang