apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: applications.dmaganto.infra
spec:
  group: dmaganto.infra
  scope: Namespaced
  names:
    kind: Application
    singular: application
    plural: applications
    shortNames:
    - apps
    categories:
    - all
  versions:
  - name: v1alpha1
    served: true
    storage: true
    additionalPrinterColumns:
      - name: team
        type: string
        description: Team
        jsonPath: .spec.team
      - name: slack
        type: string
        description: Slack Channel
        jsonPath: .spec.slackChannel
      - name: Age
        type: date
        jsonPath: .metadata.creationTimestamp
    schema:
      openAPIV3Schema:
        type: object
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              team:
                type: string
                enum:
                  - claims
                  - front
                  - back
              slackChannel: 
                type: string
            required:
              - team
              - slackChannel
            type: object